version: '3'
services:
  tarin:
    image: dilshadbanu/phonepaytrain:v1
    ports:
      - "8008:80"
    deploy:
      replicas: 3

  movie:
    image: dilshadbanu/ubuntu
    ports:
      - "8009:80"
    deploy:
      replicas: 3
      
  recharge:
    image: dilshadbanu/phonepayrecharge:v1
    ports:
      - "8010:80"
    deploy:
      replicas: 3

